name: taskmaster
description: "A beautiful and powerful task management app with smart notifications."
# Prevent accidental publishing to pub.dev
publish_to: "none" # Remove this line if you wish to publish to pub.dev

flutter_native_splash:
  color: "#1E1E1E"
  image: assets/splash/splash.png
  android: true
  ios: true
  web: false
  fullscreen: true

# Application version
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  animate_do: ^4.2.0
  uuid: ^4.5.2
  introduction_screen: ^3.1.14
  flutter_localizations:
    sdk: flutter
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

# For information on the generic Dart part of this file, see the following page:
# https://dart.dev/tools/pub/pubspec

# Flutter specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: false
